spring:
  application:
    name: spring-example-gateway
  cloud:
    gateway:
      routes:
        - id: route1
          uri: http://example.com
          predicates:
            - Method=GET
          filters:
            - AddRequestHeader=X-MSP-Gateway, 1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
server:
  port: 19090
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
